AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: Provision the magic serverless infrastructure
###############################################################
Parameters:
###############################################################
  env:
    Type: String
    Default: dev
    Description: Environment Name

  project:
    Type: String
    Default: empty-project-name
    Description: Project Name
  
  description:
    Type: String
    Default: empty-project-description
    Description: Project Description
###############################################################
Resources:
###############################################################
  LambdaFunction:
    Type: 'AWS::Serverless::Function'
    Properties:
      FunctionName: !Sub ${project}-${env}
      Description: !Sub ${description}
      Handler: handlers.main
      Runtime: python3.7
      CodeUri: ./build
      MemorySize: 128
      Timeout: 3
      Policies:
        - AWSLambdaExecute # Managed Policy
        - Version: '2012-10-17' # Policy Document
          Statement:
            - Effect: Allow
              Action:
              - ec2:DescribeRegions
              - ec2:DescribeInstances
              - ec2:DescribeInstanceStatus
              - ses:SendEmail
              - iam:GetRole
              - iam:ListAccountAliases
              Resource: 'least_privilege_please'
      Events:
        Timer:
          Type: Schedule
          Properties:
            Schedule: rate(1 day)
      Tags:
        Project: !Sub ${project}

